import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BookOpen, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, Feather, Heart, LogOut, Menu, MoreHorizontal, PenLine, Plus, Search, Settings, Sparkles, Tags, Trash2, X } from 'lucide-react'
import { authApi } from '../lib/auth'
import { entriesApi } from '../lib/entries'

const moods = [{ icon: '☀', label: 'Happy' }, { icon: '◐', label: 'Calm' }, { icon: '✦', label: 'Inspired' }, { icon: '♥', label: 'Loved' }, { icon: '☁', label: 'Low' }]
const blankEntry = () => ({ title: '', text: '', mood: '', tags: [], date: new Date().toISOString().slice(0, 10) })
const moodIcon = mood => moods.find(m => m.label.toLowerCase() === String(mood).toLowerCase())?.icon || '•'
const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000/api'
const keepServerAwake = () => fetch(`${API_URL}/health`).catch(() => {})
function Logo() { return <div className="brand"><span className="brand-mark">d</span><span>daymark</span></div> }

function App() {
  const [screen, setScreen] = useState('loading'), [active, setActive] = useState('Today'), [menuOpen, setMenuOpen] = useState(false), [mobileNavOpen, setMobileNavOpen] = useState(false)
  const [user, setUser] = useState(null), [entries, setEntries] = useState([]), [entry, setEntry] = useState(blankEntry()), [notice, setNotice] = useState(''), [confirmDelete, setConfirmDelete] = useState(false)
  const loadEntries = async () => { const result = await entriesApi.list(); setEntries(result.entries); return result.entries }
  useEffect(() => { if (!localStorage.getItem('daymark_token')) return setScreen('login'); authApi.me().then(({ user }) => { setUser(user); setScreen('app'); return loadEntries() }).catch(() => { localStorage.removeItem('daymark_token'); setScreen('login') }) }, [])
  useEffect(() => {
    if (screen !== 'app') return undefined
    keepServerAwake()
    const syncTimer = window.setInterval(() => { keepServerAwake(); loadEntries().catch(() => {}) }, 60_000)
    return () => window.clearInterval(syncTimer)
  }, [screen])
  const signedIn = async session => { localStorage.setItem('daymark_token', session.token); setUser(session.user); setScreen('app'); await loadEntries() }
  const signOut = async () => { try { await authApi.logout() } catch {} localStorage.removeItem('daymark_token'); setUser(null); setEntry(blankEntry()); setScreen('login') }
  const beginNew = () => { setEntry(blankEntry()); setConfirmDelete(false); setMobileNavOpen(false); setActive('Today') }
  const beginNewForDate = date => { setEntry({ ...blankEntry(), date }); setConfirmDelete(false); setMobileNavOpen(false); setActive('Today') }
  const openEntry = item => { setEntry(item); setConfirmDelete(false); setMobileNavOpen(false); setActive('Today') }
  const saveEntry = async () => { if (!entry.title && !entry.text) return setNotice('Write a little before saving.'); try { const result = entry.id ? await entriesApi.update(entry.id, entry) : await entriesApi.create(entry); setEntry(result.entry); await loadEntries(); setNotice('Saved ✓') } catch (e) { setNotice(e.message) } setTimeout(() => setNotice(''), 1800) }
  const deleteEntry = async () => { if (!entry.id) return; try { await entriesApi.remove(entry.id); await loadEntries(); setEntry(blankEntry()); setConfirmDelete(false); setNotice('Entry deleted'); setTimeout(() => setNotice(''), 1800) } catch (e) { setConfirmDelete(false); setNotice(e.message); setTimeout(() => setNotice(''), 2500) } }
  if (screen === 'loading') return null
  if (screen === 'login') return <Login onSuccess={signedIn} />
  return <div className="app-shell"><button className={mobileNavOpen ? 'mobile-scrim visible' : 'mobile-scrim'} onClick={() => setMobileNavOpen(false)} aria-label="Close navigation"/><aside className={mobileNavOpen ? 'sidebar mobile-open' : 'sidebar'}><Logo /><button className="new-entry" onClick={beginNew}><Plus size={17} /> New entry <span>⌘ N</span></button><nav>{[['Today', Feather], ['All entries', BookOpen], ['Calendar', CalendarDays], ['Tags', Tags]].map(([label, Icon]) => <button key={label} className={active === label ? 'nav-item selected' : 'nav-item'} onClick={() => { setActive(label); setMobileNavOpen(false) }}><Icon size={18} />{label}</button>)}</nav><div className="sidebar-footer"><button className="nav-item"><Settings size={18} />Settings</button><button className="profile" onClick={() => setMenuOpen(!menuOpen)}><div className="avatar">{user?.initials}</div><span><b>{user?.name}</b><small>View profile</small></span><ChevronDown size={15} /></button>{menuOpen && <div className="profile-menu"><button onClick={signOut}><LogOut size={15}/> Sign out</button></div>}</div></aside><main className="workspace"><header className="mobile-header"><button onClick={() => setMobileNavOpen(true)} aria-label="Open navigation"><Menu size={21}/></button><Logo /><button onClick={beginNew} aria-label="New entry"><Plus size={21}/></button></header>{active === 'Today' && <Editor entry={entry} setEntry={setEntry} onSave={saveEntry} onDelete={() => setConfirmDelete(true)} notice={notice} />}{active === 'All entries' && <Entries entries={entries} onNew={beginNew} onOpen={openEntry} />}{active === 'Calendar' && <Calendar entries={entries} onOpen={openEntry} onNew={beginNewForDate} />}{active === 'Tags' && <TagsView entries={entries} onOpen={openEntry} />}</main>{confirmDelete && <DeleteDialog title={entry.title} onCancel={() => setConfirmDelete(false)} onConfirm={deleteEntry} />}</div>
}

function Login({ onSuccess }) {
  const [isSignUp, setIsSignUp] = useState(false), [showPass, setShowPass] = useState(false), [name, setName] = useState(''), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const submit = async e => { e.preventDefault(); setError(''); setBusy(true); try { await onSuccess(isSignUp ? await authApi.register({ name, email, password }) : await authApi.login({ email, password })) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <div className="login-page"><div className="login-art"><Logo /><div className="art-copy"><span className="eyebrow">YOUR PERSONAL CORNER</span><h1>Keep the days<br/><em>that keep you.</em></h1><p>A private space for your thoughts, moments, and the beautifully ordinary in between.</p></div><div className="paper paper-one"/><div className="paper paper-two"><span>sept 12</span><i>☼</i><p>Today, I noticed...</p><div/><div/><div/></div><span className="art-note">made for your inner world</span></div><section className="login-form"><form className="form-inner" onSubmit={submit}><div className="form-heading"><h2>{isSignUp ? 'Begin your journal' : 'Welcome back'}</h2><p>{isSignUp ? 'A few words now. A lifetime to look back on.' : 'Your thoughts have been waiting for you.'}</p></div>{isSignUp && <label>Your name<input required value={name} onChange={e => setName(e.target.value)} placeholder="What should we call you?" /></label>}<label>Email address<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>Password<div className="password"><input required minLength="6" value={password} onChange={e => setPassword(e.target.value)} type={showPass ? 'text' : 'password'} placeholder="••••••••"/><button type="button" onClick={() => setShowPass(!showPass)}>{showPass ? 'Hide' : 'Show'}</button></div></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Please wait…' : isSignUp ? 'Create my diary' : 'Enter daymark'} <ArrowRight size={17}/></button><p className="switch">{isSignUp ? 'Already have a diary?' : 'New to daymark?'} <button type="button" onClick={() => { setIsSignUp(!isSignUp); setError('') }}>{isSignUp ? 'Sign in' : 'Create one'}</button></p><p className="privacy">Your diary is private. Always.</p></form></section></div>
}

function Editor({ entry, setEntry, onSave, onDelete, notice }) { const [tagInput, setTagInput] = useState(''); const addTag = () => { const tag = tagInput.trim().replace(/^#/, ''); if (tag && !entry.tags.includes(tag)) setEntry({ ...entry, tags: [...entry.tags, tag] }); setTagInput('') }; const date = new Date(`${entry.date}T12:00:00`); return <div className="editor-page"><header className="editor-top"><div><span className="eyebrow">{entry.id ? 'EDITING MEMORY' : date.toLocaleDateString(undefined, { weekday: 'long' }).toUpperCase()}</span><h1>{date.toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' })}</h1></div><div className="top-actions">{entry.id && <button className="delete-button" onClick={onDelete}><Trash2 size={16}/> Delete</button>}<button className="icon-button" aria-label="More entry options"><MoreHorizontal size={20}/></button><button className="save" onClick={onSave}>{notice || 'Save entry'}</button></div></header><section className="editor-card"><div className="writing"><input className="entry-title" value={entry.title} onChange={e => setEntry({ ...entry, title: e.target.value })} placeholder="Title your day..."/><textarea value={entry.text} onChange={e => setEntry({ ...entry, text: e.target.value })} placeholder="How was your day?"/><div className="entry-bottom"><div className="tag-row">{entry.tags.map(t => <button className="tag removable" onClick={() => setEntry({ ...entry, tags: entry.tags.filter(x => x !== t) })} key={t}>#{t} ×</button>)}<input className="tag-input" value={tagInput} onChange={e => setTagInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && (e.preventDefault(), addTag())} placeholder="add tag"/><button className="add-tag" onClick={addTag}><Plus size={14}/> tag</button></div><span className="word-count">{entry.text.trim() ? entry.text.trim().split(/\s+/).length : 0} words</span></div></div><aside className="reflection"><span className="eyebrow">HOW ARE YOU FEELING?</span><div className="current-mood">{moodIcon(entry.mood)}<b>{entry.mood || 'Choose a mood'}</b></div><div className="mood-list">{moods.map(m => <button key={m.label} className={entry.mood === m.label ? 'mood picked' : 'mood'} onClick={() => setEntry({ ...entry, mood: m.label })}><span>{m.icon}</span>{m.label}</button>)}</div><div className="prompt"><Sparkles size={16}/><div><b>A little prompt</b><p>What made you smile today?</p></div></div></aside></section></div> }

function DeleteDialog({ title, onCancel, onConfirm }) { return <div className="dialog-backdrop" role="presentation" onMouseDown={onCancel}><section className="delete-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-title" onMouseDown={e => e.stopPropagation()}><div className="delete-icon"><Trash2 size={21}/></div><h2 id="delete-title">Delete this entry?</h2><p>{title ? <>“{title}” will be permanently removed.</> : 'This entry will be permanently removed.'} This can’t be undone.</p><div className="dialog-actions"><button className="cancel-button" onClick={onCancel}>Keep entry</button><button className="confirm-delete" onClick={onConfirm}><Trash2 size={15}/> Delete entry</button></div></section></div> }

function Entries({ entries, onNew, onOpen }) { const [search, setSearch] = useState(''); const filtered = useMemo(() => entries.filter(e => `${e.title} ${e.text} ${e.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase())), [entries, search]); return <div className="list-page"><header className="list-header"><div><span className="eyebrow">YOUR COLLECTION</span><h1>All entries <small>{entries.length} memories</small></h1></div><button className="new-entry dark" onClick={onNew}><Plus size={17}/> New entry</button></header><div className="search"><Search size={18}/><input placeholder="Search your memories..." value={search} onChange={e=>setSearch(e.target.value)}/>{search && <button onClick={()=>setSearch('')} aria-label="Clear search"><X size={16}/></button>}</div><div className="entry-grid">{filtered.map(e => <article className="entry-preview" tabIndex="0" role="button" onClick={() => onOpen(e)} onKeyDown={event => event.key === 'Enter' && onOpen(e)} key={e.id}><div className="date-block" style={{background:'#b9c8a5'}}><b>{new Date(`${e.date}T12:00`).toLocaleDateString(undefined,{month:'short'}).toUpperCase()}</b><strong>{e.date.slice(-2)}</strong><span>{e.date.slice(0,4)}</span></div><div><div className="preview-meta"><span>{moodIcon(e.mood)} {e.mood || 'unmarked'}</span><span>{Math.max(1, Math.ceil(e.text.split(/\s+/).filter(Boolean).length / 200))} min read</span></div><h2>{e.title || 'Untitled day'}</h2><p>{e.text || 'No words yet.'}</p><div className="tag-row">{e.tags.map(t=><span className="tag" key={t}>#{t}</span>)}</div></div></article>)}</div>{!filtered.length && <div className="empty-state"><BookOpen size={24}/><p>No entries found. Start with one honest moment.</p>{!search && <button className="text-action" onClick={onNew}>Write an entry <ArrowRight size={14}/></button>}</div>}</div> }
function Calendar({ entries, onOpen, onNew }) {
  const today = new Date()
  const [visibleMonth, setVisibleMonth] = useState(() => new Date(today.getFullYear(), today.getMonth(), 1))
  const [selectedDate, setSelectedDate] = useState(() => today.toISOString().slice(0, 10))
  const y = visibleMonth.getFullYear(), m = visibleMonth.getMonth()
  const count = new Date(y, m + 1, 0).getDate(), first = (new Date(y, m, 1).getDay() + 6) % 7
  const monthKey = `${y}-${String(m + 1).padStart(2, '0')}`
  const entriesByDate = entries.filter(e => e.date.startsWith(monthKey)).reduce((all, item) => ({ ...all, [item.date]: [...(all[item.date] || []), item] }), {})
  const selectedEntries = entriesByDate[selectedDate] || []
  const dayLabel = new Date(`${selectedDate}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })
  const changeMonth = offset => { const next = new Date(y, m + offset, 1); setVisibleMonth(next); setSelectedDate(`${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}-01`) }
  const selectDay = day => setSelectedDate(`${monthKey}-${String(day).padStart(2, '0')}`)
  const daysRemembered = Object.keys(entriesByDate).length
  return <div className="calendar-page"><header className="calendar-heading"><div><span className="eyebrow">LOOKING BACK</span><h1>{visibleMonth.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</h1></div><div className="month-actions"><button className="today-button" onClick={() => { setVisibleMonth(new Date(today.getFullYear(), today.getMonth(), 1)); setSelectedDate(today.toISOString().slice(0, 10)) }}>Today</button><div className="month-nav"><button onClick={() => changeMonth(-1)} aria-label="Previous month"><ChevronLeft size={18}/></button><button onClick={() => changeMonth(1)} aria-label="Next month"><ChevronRight size={18}/></button></div></div></header><div className="calendar-layout"><div className="calendar"><div className="weekdays">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d => <span key={d}>{d}</span>)}</div><div className="date-grid">{Array.from({ length: first }, (_, i) => <i key={`blank-${i}`}/>)}{Array.from({ length: count }, (_, i) => i + 1).map(day => { const iso = `${monthKey}-${String(day).padStart(2, '0')}`, items = entriesByDate[iso] || [], isToday = iso === today.toISOString().slice(0, 10), isSelected = iso === selectedDate; return <button className={`${items.length ? 'has-entry ' : ''}${isToday ? 'today ' : ''}${isSelected ? 'selected-day' : ''}`} onClick={() => selectDay(day)} aria-label={`${day}, ${items.length} ${items.length === 1 ? 'entry' : 'entries'}`} key={day}><span>{day}</span>{items.length > 0 && <div className="day-markers">{items.slice(0, 3).map(item => <em key={item.id}>{moodIcon(item.mood)}</em>)}{items.length > 3 && <b>+{items.length - 3}</b>}</div>}</button> })}</div></div><aside className="day-detail"><div className="day-detail-heading"><div><span className="eyebrow">SELECTED DAY</span><h2>{dayLabel}</h2></div><span className="entry-count">{selectedEntries.length} {selectedEntries.length === 1 ? 'entry' : 'entries'}</span></div>{selectedEntries.length ? <div className="day-entry-list">{selectedEntries.map(item => <button className="day-entry" onClick={() => onOpen(item)} key={item.id}><span className="day-entry-mood">{moodIcon(item.mood)}</span><span><b>{item.title || 'Untitled day'}</b><small>{item.text || 'No words yet.'}</small></span><ArrowRight size={15}/></button>)}</div> : <div className="empty-day"><CalendarDays size={20}/><p>No memory here yet.</p><button onClick={() => onNew(selectedDate)}><PenLine size={14}/> Write for this day</button></div>}</aside></div><div className="calendar-note"><Heart size={17}/><span><b>{daysRemembered} {daysRemembered === 1 ? 'day' : 'days'} remembered</b> in {visibleMonth.toLocaleDateString(undefined, { month: 'long' })}. Keep going, one honest moment at a time.</span></div></div>
}
function TagsView({ entries, onOpen }) { const tags = Object.entries(entries.flatMap(e=>e.tags).reduce((a,t)=>(a[t]=(a[t]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]); return <div className="tags-page"><span className="eyebrow">YOUR THREADS</span><h1>Tags</h1><p>Small markers that help you find the moments that matter.</p><div className="tags-grid">{tags.map(([tag,count], i)=><button key={tag} onClick={() => onOpen(entries.find(e=>e.tags.includes(tag)))}><span style={{background:['#b9c8a5','#d9c6a7','#a9c6d9','#e7a9a2'][i%4]}}>#</span><b>{tag}</b><small>{count} {count === 1 ? 'entry' : 'entries'}</small><ArrowRight size={16}/></button>)}</div>{!tags.length && <p className="empty-state">Tags you add to entries will appear here.</p>}</div> }
export default App
